export const translations = {
  en: {
    
    general: "General",
    workspaceManagement: "Workspace Management",
    whatsAppChat: "WhatsApp Chat",
    liveChat: "Live Chat",
    broadcast: "Broadcast",
    contacts: "Contacts",
    fileManager: "File Manager",
    notifications: "Notifications",
    language: "Language",
    settings: "Settings",
    teams: "Teams",
    users: "Users",
    email: "Email",
    password: "Password",
    agreeTextPart1: "",
    and: "and",
    terms: "Terms of services",
    privacyPolicy: "Privacy Policy",
    businessAdmin: "Business admin",
    dashboard: "Dashboard",
    createAgent: "Create Agent",
    createNewAgent: "Create New Agent",
    uploadProfilePhotoOptional: "Upload Profile Photo (optional)",
    chooseFile: "Choose file",
    namePlaceholderAgent: "Pedro Duarte",
    whatsAppNumber: "WhatsApp Number",
    emailAddress: "Email Address",
    enterAgentEmail: "Enter agent's work email",
    role: "Role",
    roleAgent: "Agent",
    roleSupervisor: "Supervisor",
    roleAdmin: "Admin",
    activeStatus: "Active Status",
    activeStatusHint: "Agent can log in and receive chats",
    cancel: "Cancel",
    allMessages: "All messages",
    unattended: "Unattended",
    searchByNameOrPhone: "Search with name or phone",
    manage: "Manage",
    filter: "Filter",
    all: "All",
    mine: "Mine",
    unassigned: "Unassigned",
    replyTimer: "15h left for reply",
    seeContact: "See contact",
    typeMessage: "Type your message here...",
    send: "Send",
    // add inside translations.en
    goodEvening: "Good evening",
    userName: "Anas",
    dashboardSubtitle2: "Here is the overview about how business gaining lead.",
    lastMonth: "Last month",
    last3Months: "Last 3 months",
    lastSixMonths: "Last 6 months",
    lastYear: "Last 12 months",

    openConversation: "Open Conversation",
    totalConversation: "Total Conversation",
    chatbotSessions: "Chatbot Sessions",
    fromLastMonth: "from last month",

    total: "Total",
    currentlyActive: "Currently active",
    newAdded: "New added",
    campaigns: "Campaigns",

    conversations: "Conversations",
    weekly: "Weekly",
    monthly: "Monthly",
    open: "Open",
    closed: "Close",

    messages: "Messages",
    sent: "Sent",
    received: "Received",
    read: "Read",
    failed: "Failed",

    conversationByAgents: "Conversation by Agents",
    agents: "Agents",
    pending: "Pending",
    close: "Close",
    rating: "Rating",
    loginTitle: "Login to your account",
    loginSubtitle: "sign-in to your account and start the adventure",
    signIn: "Sign In",
    resetPassword:"Reset Password"

  },
  ar: {
    general: "عام",
    workspaceManagement: "إدارة مساحة العمل",
    whatsAppChat: "دردشة واتساب",
    liveChat: "الدردشة المباشرة",
    broadcast: "البث",
    contacts: "جهات الاتصال",
    fileManager: "مدير الملفات",
    notifications: "الإشعارات",
    language: "اللغة",
    settings: "الإعدادات",
    teams: "الفرق",
    users: "المستخدمون",
    businessAdmin: "إدارة الأعمال",
    dashboard: "لوحة التحكم",
    goodEvening: "مساء الخير",
    userName: "أنس",
    dashboardSubtitle2: "إليك نظرة عامة عن تقدّم الأعمال في اكتساب العملاء.",
    lastMonth: "الشهر الماضي",
    last3Months: "آخر 3 أشهر",
    lastSixMonths: "آخر 6 أشهر",
    lastYear: "آخر 12 شهرًا",

    openConversation: "المحادثات المفتوحة",
    totalConversation: "إجمالي المحادثات",
    chatbotSessions: "جلسات روبوت الدردشة",
    fromLastMonth: "عن الشهر الماضي",

    total: "الإجمالي",
    currentlyActive: "النشط حاليًا",
    newAdded: "المضاف حديثًا",
    campaigns: "الحملات",

    conversations: "المحادثات",
    weekly: "أسبوعي",
    monthly: "شهري",
    open: "مفتوحة",
    unassigned: "غير مسنّدة",
    closed: "مغلقة",

    messages: "الرسائل",
    sent: "المُرسلة",
    received: "الواردة",
    read: "المقروءة",
    failed: "الفاشلة",

    conversationByAgents: "المحادثات حسب الوكلاء",
    agents: "الوكلاء",
    pending: "قيد الانتظار",
    close: "إغلاق",
    rating: "التقييم",

    allMessages: "كل الرسائل",
    unattended: "غير المتابعة",
    searchByNameOrPhone: "ابحث بالاسم أو رقم الهاتف",
    manage: "إدارة",
    filter: "تصفية",
    all: "الكل",
    mine: "خاصة بي",
    replyTimer: "متبقي 15 ساعة للرد",
    seeContact: "عرض جهة الاتصال",
    typeMessage: "اكتب رسالتك هنا...",
    send: "إرسال",
    createAgent: "إنشاء وكيل",
    createNewAgent: "إنشاء وكيل جديد",
    uploadProfilePhotoOptional: "رفع صورة الملف الشخصي (اختياري)",
    chooseFile: "اختيار ملف",
    namePlaceholderAgent: "بيدرو دوارتي",
    whatsAppNumber: "رقم واتساب",
    emailAddress: "البريد الإلكتروني",
    enterAgentEmail: "أدخل بريد العمل للوكيل",
    role: "الدور",
    roleAgent: "وكيل",
    roleSupervisor: "مشرف",
    roleAdmin: "مسؤول",
    activeStatus: "الحالة النشطة",
    activeStatusHint: "يمكن للوكيل تسجيل الدخول واستقبال المحادثات",
    cancel: "إلغاء",
    loginTitle: "تسجيل الدخول إلى حسابك",
    loginSubtitle: "سجّل الدخول إلى حسابك وابدأ المغامرة",
    
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    agreeTextPart1: "من خلال تسجيل الدخول، فإنك توافق على",
    and: "و",
    terms: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    signIn: "تسجيل الدخول",
    resetPassword: "إعادة تعيين كلمة المرور",
  },
};
